### ISSUE TITLE
Support for httpApi event?

### ISSUE THREAD

**Issue by natac13** [DianaIonita/serverless-api-gateway-throttling#7]
Hey, I am just wondering if this plugin supports throttling for httpApi events as well as http?

**Comment by DianaIonita** [comment]
Hi @natac13,

The plugin doesn't officially support httpApi events currently. Support may be added in the future, but there aren't any plans right now.

**Comment by fcrdossantos** [comment]
Hi, does the plugin support the usage httpApi now?
If not, do you have any recommendatiopns to apply a throttling with httpApi (api gateway v2)?

**Comment by DianaIonita** [comment]
Hi @fcrdossantos,

The plugin doesn't currently support httpApi, mainly because I've not had the chance to work with API Gateway v2 yet and I'm unaware of how it might be different from v1.
I see that there's reasonable demand for it, so I'll start looking into how it may be implemented. I'll update this thread when I have updates, e.g. it's not needed or not possible, or it's done.

**Comment by DianaIonita** [comment]
Hi everyone,

Version [2.0.0](https://github.com/DianaIonita/serverless-api-gateway-throttling/releases/tag/2.0.0) of this plugin has been released and it now supports Http APIs. If you encounter any issues, please raise them as separate tickets.
